### ISSUE TITLE
Units?

### ISSUE THREAD

**Issue by madeleinea** [cortex-lab/KiloSort#105]
I'm wondering what units the following parameters are in: ops.Th and ops.lam. 

Thanks!

**Comment by marius10p** [comment]
The data is whitened so that each channel has a variance of 1 and approximately no correlation with other channels. The unit-norm template is then dot multiplied with the raw data. The resulting number is then the best estimate of the amplitude of that spike on this template. If that amplitude is lower than ops.Th, it does not get assigned. If it's further away than 2*ops.lam from the mean amplitude of the template, it again does not get assigned.  These statements are approximately correct: the exact formal criterion is described in the paper.
