### ISSUE TITLE
Common Average Referencing

### ISSUE THREAD

**Issue by angelonc** [cortex-lab/KiloSort#155]
Hi, this isn't really an issue, but more of a question, related to openEphys' online CAR filter and whether I should use this in KiloSort.

I recently started saving the CAR data from the openEphys acquisition system and feeding it into KiloSort. When I examine the waveforms in Phy, it seems like the CAR is having the effect of creating an inverted spike waveform in the other channels. This makes perfect sense, as each spike should contribute to the average and thus be subtracted from the other channels.

![car_artifact](https://user-images.githubusercontent.com/3865975/44168396-25d8a780-a09f-11e8-9988-b89a7c13904b.PNG)

However, should I be worried that these inverted spikes will be detected as clusters? Are there any other considerations for using CAR'ed data in KiloSort or any conventions that people use? I've re-referenced some data by hand using the mean over time, but I noticed that some people use the median instead. Is there an advantage to using the mean versus the median?

Tagging @nsteinme because he seems like a CAR fiend!

**Comment by nsteinme** [comment]
Using the median rather than the mean in generating the 'average' to subtract is a way to try to get around this issue - I don't know what openephys does. It may also be the case that 16 channels is too few to avoid this problem. The original paper (Ludwig et al J Neurophys 2009) was with 16 channel arrays iirc but it'll depend on how dense the sites are and how big the neurons. 

That said, I think this is likely to be a cosmetic problem rather than a real one. I can't think of how these little positive parts of the spikes would actually impair kilosort in any way, and any noise you have that's truly identical on all channels really will be subtracted out. So I think it's still a win. If you keep the original data you could add back the median when computing mean waveforms if you want them to look right. hth-

**Comment by marius10p** [comment]
I can confirm that Kilosort doesn't care.

**Comment by angelonc** [comment]
Thanks for your responses!

Just so I understand, the median should be less affected by outliers, so this makes it less sensitive to spikes on a small number of channels compared to the mean.

**Comment by nsteinme** [comment]
Yes that's right, e.g. if your true spike shows up on 4 out of 16 channels
but is large on those channels, the median will not be much influenced by
it but the mean will look like a small version of it.
