### ISSUE TITLE
installation issue on windows 10

### ISSUE THREAD

**Issue by rajatsaxena** [cortex-lab/KiloSort#170]
I have been trying to setup kilosort on windows 10 and have been getting the same error again and again. When I run 'mexGPUall.m', this is the error I get:

<img width="459" alt="capture2" src="https://user-images.githubusercontent.com/5181888/48523761-99bb5500-e832-11e8-96a5-79c72f5e1743.PNG">

I have followed the exact same steps as the Readme file. 

Current my system config is follows:
Matlab 2018a, Windows Visual Studio C++ 2013 and Cuda 9.0

Let me know if you need any more information. Thanks!

**Comment by BbKbyers15** [comment]
Hello I am having the same issue with installation on windows 10. I have downloaded Matlab 2019a, Visual Studio Community 2013 and Cuda 9.0. When I try to select the proper compiler per the installation instructions I get the following output:

>> mex -setup C++ 
MEX configured to use 'MinGW64 Compiler (C++)' for C++ language compilation.
Warning: The MATLAB C and Fortran API has changed to support MATLAB
	 variables with more than 2^32-1 elements. You will be required
	 to update your code to utilize the new API.
	 You can find more information about this at:
	 https://www.mathworks.com/help/matlab/matlab_external/upgrading-mex-files-to-use-64-bit-api.html.api.html.

So its not able to locate the 2013 edition of MS Visual systems even though I've successfully installed it. I've tried to reinstall MS Visual Systems 2013 since the files "msvc2013.xml" and "msvcpp2013.xml" do not exist in "MATLABROOT\bin\win64\mexopts" but this did not solve the problem either. Let me know if you need any more information about my problem. Thanks!

**Comment by OptogeneticsandNeuralEngineeringCore** [comment]
Note: this happens because of Matlab 2019a installation. I spent quite a bit of time today with this, trying different versions of lots of things (it seems like a VS 2013 issue), but ultimately found that this is due to Matlab 2019a. 

I think the instructions should be updated to state that users should use ONLY 2018a, not 2018a and newer.
