### ISSUE TITLE
test performance for correctly detecting neurons with small numbers of spikes.

### ISSUE THREAD

**Issue by nsteinme** [cortex-lab/KiloSort#4]
I.e. create a ground-truth file with a cluster inserted at several different amplitudes/positions. Pick one or more of these amplitude-position combinations and create GT files with progressively fewer numbers of spikes. 

One thing that might make this sort of thing convenient could be if the SVD-reconstructed waveforms were all stored in a library, such that they could quickly be called up and inserted into the raw data on the fly (rather than computing them and creating a whole new GT file on the hard drive). Let me know if that would be useful, I could do it. An even shorter cut, of course, would be to simply take a generic waveform shape and insert it into the file - this would probably be fine as a first pass, e.g. in this case for diagnosing whether there are any fundamental problems with small numbers of spikes.

**Comment by marius10p** [comment]
There is now a complete simulation in Kilosort using waveforms detected from one of your real experiments. This can be used, in principle, for studying how performance varies with the number of spikes in a cluster. The short answer is that most clusters <2% of the maximum number of spikes / neuron are not detected in Kilosort. Will need special provisions for finding such low firing neurons, because the variance explained criterion favors quantity over quality.
