### ISSUE TITLE
common average referencing & independent channels 

### ISSUE THREAD

**Issue by MartinKahn** [cortex-lab/KiloSort#70]
Hi, 

Sorry if these questions are a bit simple. Just getting started with spike sorting... 

i) In the bioRxiv paper, you use common average referencing as part of the pre-processing. Is this part of the kilosort pre-processing script? I had a look at the scripts and couldn't (trivially) locate it. 

ii) One of our experiments involves 8x8 MUAs with 200uM spacing, so there's a very small chance for shared spikes. Do I correctly assume that the only parameter I really need to worry about is 'kcoords = 1:nChannels' ? 

Thanks!

**Comment by marius10p** [comment]
Hi Martin,

i) I think we might have taken that out, because the whitening step already does that implicitly. If you want to check out proper CAR, you could run it on your data first, or  add it as an option to the preprocessing script. 

ii) Yes, that configuration of kcoords will ensure that 80% of the clusters are single channel. The other 20% are allowed to live on the entire array to take into account noise, which is usually global. You can adjust this ratio using one of the parameters (see the createChannelMap script).

**Comment by nsteinme** [comment]
There is a function to do CAR here: https://github.com/cortex-lab/spikes/blob/master/preprocessing/applyCARtoDat.m

It was described in the paper because I always do it on my data first, but I don't think it has ever been part of Kilosort. It will be a bad idea if you have a small number of channels (like 8 or fewer). Otherwise there is no reason not to do it.

**Comment by MartinKahn** [comment]
Thanks a lot guys!

**Comment by ChauhanT** [comment]
@nsteinme  Hi, the code snippet you shared does median referencing for both time and channels. In the biorxiv pre-print [[link]](https://www.biorxiv.org/content/10.1101/2023.01.07.523036v1.full.pdf) CAR is done via a mean over time and median over channels. I was wondering if there are demonstrated advantages of one over the other (besides the computational simplicity of mean over the median, especially for very large arrays).
