### ISSUE TITLE
Clusters with high similarity - Peak Amp offset in time

### ISSUE THREAD

**Issue by Sarruedi** [cortex-lab/KiloSort#85]
Sometimes I get clusters which have a high similarity score (eg. 0.9) but the waveforms seem shifted in time in the waveform view as the waveforms are not peak aligned in the display in phy. Now I am unsure whether I should still merge these clusters based on the waveform similarity/amplitude/pc features or whether the offset in time is actually indicative of being a different unit. The data has been sorted in KiloSort and it might be caused in the sorting step in KiloSort or simply be a display issue in phy.

Based on the ACG/PC features for such clusters, I think the clusters actually arise from same unit but it seems that they either end up with a different timestamp for the peak in LioSort or display in phy does not align spikes based on the peak amplitude but some earlier bin. 

Does anyone know how the waveforms are put in relation to each other in phy? 
How could highly similar clusters not be peak aligned in time in relation to each other?

**Comment by greggheller** [comment]
I have had this problem as well. 

I think it is because of the way kilosort updates the templates. If there is a predictable voltage change before the spike, then that gets incorporated into the template. The templates/waveforms must be aligned in phy by the beginning of the template rather than the peak time. 

It is nice that the similarity score still identifies these clusters as similar but it would be really nice if we could align the waveforms/templates by the peak time. This would make the decision much easier when other indicators are ambiguous.  

I am also interested in learning how the similarity score is calculated, and would like to second Sarah's questions.

**Comment by greggheller** [comment]
Here are two examples
![templates not aligned example in time](https://user-images.githubusercontent.com/28813604/30504137-ee308552-9a21-11e7-8ea5-23ff96605258.PNG)
![templates not aligned example in time2](https://user-images.githubusercontent.com/28813604/30504138-ee30a08c-9a21-11e7-9c94-04905642940d.PNG)

**Comment by LongLabGit** [comment]
We have encountered the same issue: 
![image](https://user-images.githubusercontent.com/29983043/31101447-b8c54b0a-a79b-11e7-9e86-5cec0a2d1edd.png)
![image](https://user-images.githubusercontent.com/29983043/31101457-c3f44b7a-a79b-11e7-9e0c-e9b1c1018a90.png)

**Comment by nsteinme** [comment]
Hi all - sorry for the very slow response on this. 

First a clarification: phy (the GUI software) does not do anything with aligning waveforms, it simply displays the waveforms according to the timestamps it is given. So the fact that you get two templates with similar shapes but mis-aligned is on kilosort's end. 

But spike alignment is a really hard problem - there's plenty of discussion in the literature about this. Kilosort takes the typical approach of aligning to the negative peak, which runs into problems when there are two channels that have similar peak amplitudes but are offset in time - that appears to be the case with channels 51 and 63 in the LongLab example. The red cluster are the spikes where 63 (the earlier site) were larger amplitude, and the blue cluster is those for which channel 51 were larger amplitude. 

There's really nothing to do about this except curate it manually - so yes, do merge the red and blue in @LongLabGit example. @greggheller yours is a bit harder to evaluate since we're only seeing the final merged result, but I guess you get the point. 

With spikedetekt2 we used to take a different approach to alignment, using a center of mass. This solved some situations like this, but had its own set of weird edge cases, so I think in the end we weren't particularly motivated to keep it for kilosort. 

So I'm going to close this issue, but if you have any particular ideas/suggestions for solving this, do feel free to open a new issue. 

To answer one other specific question in this thread, the similarity score is the cross product of the two template waveform shapes. It would come out even higher if the waveforms were properly aligned, but comes out all right just because the waveforms are still largely overlapping, even when shifted.

**Comment by greggheller** [comment]
Thanks for your reply Nick. I can definitely see why it would be much harder than I had first imagined, thank you for your patience and taking the time to explain.

The only thing I can think of would be to align by the earliest/latest minimum out of the channels with similar amplitude to the peak channel. But I think this would have its own set of problems and the misalignment occurs so infrequently that it isn't worth worrying about at all.
