### ISSUE TITLE
missing "stack' attribute

### ISSUE THREAD

**Issue by vncntprvst** [cortex-lab/KiloSort#94]
Hi,
after opening the output params.py from the "eMouse" test data in phy, the cluster data are shown (CorrelogramView, FeatureView, etc) , but when selecting a cluster, the WaveformView does not show anything, and the command prompt says: 
[E] cli:36    An error has occurred (AttributeError): 'module' object has no attribute 'stack'
Any idea what's going on?

**Comment by nsteinme** [comment]
I think you need to upgrade numpy to the latest version in your conda env. This is a phy question so if it continues, please re-post on phy's github? Also note you can do "--debug" when you run phy to get more useful error messages (this is how I figured out to upgrade numpy when this happened to me recently, if indeed I'm correct that your issue is the same as mine was).
